version: '3'

services:

    php:
        build:
            context: ./configuration/php
        ports:
            - 9000:9000
        volumes:
            - ./volumes/nginx/:/var/www/html
            - ./configuration/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    nginx:
        image: nginx:1.13.8
        ports:
            - 80:80
        volumes:
            - ./volumes/nginx/:/var/www/html
            - ./volumes/logs:/var/log/nginx
            - ./configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:8.0.19
        ports:
            - 3306:3306
        depends_on:
            - php
        restart: always    
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./volumes/mysql_init:/docker-entrypoint-initdb.d
            - ./volumes/mysql_config:/etc/mysql/conf.d
            - ./volumes/mysql/:/var/lib/mysql
        command:
            'mysqld'
