version: '3'

services:

    php:
        container_name: metrica-php-fpm
        build:
            context: ./configuration/php
        networks:
            - metrica-network            
        ports:
            - 9200:9200
        volumes:
            - ./volumes/nginx/:/var/www/html
            - ./configuration/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always            

    nginx:
        container_name: metrica-nginx
        image: nginx:1.13.8
        networks:
            - metrica-network         
        ports:
            - 88:80
        volumes:
            - ./volumes/nginx/:/var/www/html
            - ./volumes/logs:/var/log/nginx
            - ./configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        restart: always            

    mysql:
        container_name: metrica-mysql
        image: mysql:8.0.19
        networks:
            - metrica-network         
        ports:
            - 3306:3306
        depends_on:
            - php
        restart: always    
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./volumes/mysql_init:/docker-entrypoint-initdb.d
            - ./volumes/mysql_config:/etc/mysql/conf.d
            - ./volumes/mysql/:/var/lib/mysql
        command:
            'mysqld'
networks:
    metrica-network:           
