-- Crear la base de datos db_tasks
CREATE DATABASE IF NOT EXISTS db_tasks;
CREATE DATABASE IF NOT EXISTS db_clientes_ex_crud;
CREATE DATABASE IF NOT EXISTS db_um_producto;
CREATE DATABASE IF NOT EXISTS db_um_usuarios;
CREATE DATABASE IF NOT EXISTS db_im_users;
CREATE DATABASE IF NOT EXISTS db_im_metricalab;
CREATE DATABASE IF NOT EXISTS db_im_internalprocedures;
CREATE DATABASE IF NOT EXISTS db_im_marketing;


-- Crear usuario
CREATE USER 'tasksuser'@'%' IDENTIFIED BY 'taskspassword';

-- Permisos para el nuevo usuario
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_tasks`.* TO 'tasksuser'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_clientes_ex_crud`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_um_producto`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_um_usuarios`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_users`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_metricalab`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_internalprocedures`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_marketing`.* TO 'root'@'%';


FLUSH PRIVILEGES;