-- Crear las bases de datos
CREATE DATABASE IF NOT EXISTS db_tasks;
CREATE DATABASE IF NOT EXISTS db_sayings;
CREATE DATABASE IF NOT EXISTS db_clientes_ex_crud;
CREATE DATABASE IF NOT EXISTS db_um_producto;
CREATE DATABASE IF NOT EXISTS db_um_usuarios;
CREATE DATABASE IF NOT EXISTS db_um_zipkin;
CREATE DATABASE IF NOT EXISTS db_im_users;
CREATE DATABASE IF NOT EXISTS db_im_metricalab;
CREATE DATABASE IF NOT EXISTS db_im_internalprocedures;
CREATE DATABASE IF NOT EXISTS db_im_marketing;
CREATE DATABASE IF NOT EXISTS db_testinglab;
CREATE DATABASE IF NOT EXISTS db_im_crmcore;

-- Needed sometimes in mysql 8 to allow Grant to Root : 
-- CREATE USER 'root'@'%' IDENTIFIED BY 'root';

-- Crear usuarios para base de datos
CREATE USER 'tasksuser'@'%' IDENTIFIED BY 'taskspassword';
CREATE USER 'sayingsuser'@'%' IDENTIFIED BY 'sayingspassword';
CREATE USER 'zipkinuser'@'%' IDENTIFIED BY 'zipkinpass';

-- Permisos para el nuevo usuario
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_tasks`.* TO 'tasksuser'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_sayings`.* TO 'sayingsuser'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_clientes_ex_crud`.* TO 'root'@'%';

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_um_producto`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_um_usuarios`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_um_zipkin`.* TO 'zipkinuser'@'%';

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_testinglab`.* TO 'root'@'%';

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_users`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_metricalab`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_internalprocedures`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_crmcore`.* TO 'root'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `db_im_marketing`.* TO 'root'@'%';

FLUSH PRIVILEGES;